// flow-typed signature: 693484e8850e658991e294e3d3af8a8d
// flow-typed version: <<STUB>>/yeticss_v^7.3.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yeticss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'yeticss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'yeticss/public/js/highlight.pack' {
  declare module.exports: any;
}

declare module 'yeticss/scripts/build-demo' {
  declare module.exports: any;
}

declare module 'yeticss/yeticss' {
  declare module.exports: any;
}

// Filename aliases
declare module 'yeticss/public/js/highlight.pack.js' {
  declare module.exports: $Exports<'yeticss/public/js/highlight.pack'>;
}
declare module 'yeticss/scripts/build-demo.js' {
  declare module.exports: $Exports<'yeticss/scripts/build-demo'>;
}
declare module 'yeticss/yeticss.js' {
  declare module.exports: $Exports<'yeticss/yeticss'>;
}
